# -*- coding: utf-8 -*-
"""Covid19_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjqbnlLzRS6b3F3SsTTRKz9uJnBWaMx7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Covid_19_Clean_Complete -TA Ajinkya.csv')
df

df.isnull().sum().sum()

df.info()

df.rename(columns = {'Province/State' : 'State'} , inplace=True)

df.rename(columns = {'Country/Region' : 'Country'} , inplace=True)

df

df['Date'].value_counts()

df_total = df.groupby(['Country'])[['Confirmed' , 'Deaths' , 'Recovered' , 'Active']].sum().reset_index()

df_total

df_confirm = df.groupby(['Date'])[['Confirmed']].sum().reset_index()
df_confirm

df_active = df.groupby(['Date'])[['Active']].sum().reset_index()
df_deaths = df.groupby(['Date'])[['Deaths']].sum().reset_index()
df_recover = df.groupby(['Date'])[['Recovered']].sum().reset_index()

plt.figure(figsize=(15,6))
sns.set_style('white')
sns.lineplot(x='Date' , y='Active' , data = df_active , linewidth=2, color="#2E86C1")
plt.xticks(df_active["Date"][::30], rotation=45)
plt.title(
    "Date vs Active Cases",
    fontsize=22,
    fontweight='600',
    color="#333333"  # soft dark grey
)
plt.xlabel("Date", fontsize=15,  color="#555555" , fontweight = 600)
plt.ylabel("Active Cases", fontsize=18,  color="#555555" , fontweight = 600)
plt.grid(True, alpha=0.08)
sns.despine(top=True, right=True)
plt.tight_layout()

plt.figure(figsize=(18,13))
sns.set_style('white')

# Subplot ---> Recovered
plt.subplot(2, 1, 1)
sns.lineplot(x='Date', y='Recovered', data=df_recover, linewidth=2, color="#2E86C1")
plt.xticks(df_recover["Date"][::30], rotation=45)
plt.title("Date vs Recovered Cases", fontsize=22, fontweight='600', color="#333333")
plt.xlabel("")
plt.ylabel("Recovered Cases", fontsize=16, fontweight=600)
plt.grid(True, alpha=0.08)
sns.despine(top=True, right=True)

# Subplot 2 ---> Deaths
plt.subplot(2, 1, 2)
sns.lineplot(x='Date', y='Deaths', data=df_deaths, linewidth=2, color="#2E86C1")
plt.xticks(df_deaths["Date"][::30], rotation=45)
plt.title("Date vs Deaths Cases", fontsize=22, fontweight='600', color="#333333")
plt.xlabel("Date", fontsize=15, color="#555555", fontweight=600)
plt.ylabel("Deaths Cases", fontsize=16, fontweight=600)
plt.grid(True, alpha=0.08)
sns.despine(top=True, right=True)

plt.tight_layout()
plt.show()

plt.figure(figsize=(15,6))
sns.set_style('white')
sns.lineplot(x='Date' , y='Confirmed' , data = df_confirm , linewidth=2, color="#2E86C1")
plt.xticks(df_confirm["Date"][::30], rotation=45)
plt.title(
    "Date vs Confirmed Cases",
    fontsize=22,
    fontweight='600',
    color="#333333"  # soft dark grey
)
plt.xlabel("Date", fontsize=15,  color="#555555" , fontweight = 600)
plt.ylabel("Confirmed Cases", fontsize=18,  color="#555555" , fontweight = 600)
plt.grid(True, alpha=0.08)
sns.despine(top=True, right=True)
plt.tight_layout()

# Prophet

'''
Prophet is a time series forecasting tool developed by Facebook that’s designed to be easy to use and effective for a wide range
of time series data. It’s particularly useful for data that has strong seasonal effects (like daily or weekly patterns) and includes
important dates or events that can impact the forecast.
'''
!pip install Prophet

from prophet import Prophet

#it's mandatory to give date column as ds and target as y
df_confirm.columns = ['ds' , 'y']
df_confirm
df_active.columns = ['ds' , 'y']
df_deaths.columns = ['ds' , 'y']
df_recover.columns = ['ds' , 'y']

model = Prophet()
model.fit(df_confirm)
future = model.make_future_dataframe(periods = 50)

forcast = model.predict(future)

model1 = Prophet()
model2 = Prophet()
model3 = Prophet()
model1.fit(df_active)
model2.fit(df_deaths)
model3.fit(df_recover)

future1 = model1.make_future_dataframe(periods = 50)
forcast1 = model1.predict(future1)
future2 = model2.make_future_dataframe(periods = 50)
forcast2 = model2.predict(future2)
future3 = model3.make_future_dataframe(periods = 50)
forcast3 = model3.predict(future3)

#! pip install cmdstanpy==1.0.4

forcast

forcast[['yhat_lower','yhat','yhat_upper']]

'''
ds:
This column contains the dates for which the predictions have been made. It stands for "date stamp."

yhat:
This is the predicted value (forecast) for the given date in the ds column. It represents the model's best estimate for that point in time.

yhat_upper:
This column represents the upper bound of the predicted value, which indicates the higher end of the confidence interval.
It suggests that the actual value is unlikely to exceed this amount, giving you an idea of the prediction's uncertainty.

yhat_lower:
This column represents the lower bound of the predicted value, indicating the lower end of the confidence interval. It suggests that the actual value is unlikely to be lower than this amount.
'''

model1.plot(forcast1)
plt.title("Active Cases Prediction")
plt.show()

model2.plot(forcast2)
plt.title("Recovered Patients Prediction")
plt.show()

model3.plot(forcast3)
plt.title("No. of Deaths will happen (Prediction)")
plt.show()

model.plot(forcast)
plt.title("Confirmed Cases Prediction")
plt.show()



import plotly
import plotly.express as px

world = df.groupby(['Country'])[['Confirmed' , 'Deaths' , 'Recovered' , 'Active']].sum().reset_index()
world

figure = px.choropleth(world , locations='Country' , locationmode = 'country names' , color ='Active' , hover_name = 'Country', range_color = [1,100000] ,
                       color_continuous_scale = 'Reds' ,
                       title = 'World Map showing all Active Cases')
figure.show()

figure = px.choropleth(world , locations='Country' , locationmode = 'country names' , color ='Deaths' , hover_name = 'Country', range_color = [1,100000] ,
                       color_continuous_scale = 'Blues' ,
                       title = 'World Map showing all Death Cases')
figure.show()

import pandas as pd
import plotly.express as px

df_long = df.groupby(
    ['Date', 'Country']
)[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().reset_index()

# Reshape the data into LONG format for animation
df_melt = df_long.melt(
    id_vars=['Date', 'Country'],
    value_vars=['Confirmed', 'Deaths', 'Recovered', 'Active'],
    var_name='Case_Type',
    value_name='Count'
)

# Sort dates for smooth animation
df_melt = df_melt.sort_values('Date')

fig = px.choropleth(
    df_melt,
    locations='Country',
    locationmode='country names',
    color='Count',
    hover_name='Country',
    animation_frame='Date',
    facet_col='Case_Type',
    facet_col_wrap=2,
    color_continuous_scale='viridis',
    title='🌍 Global COVID-19 Spread Over Time (Confirmed, Deaths, Recovered, Active)',
)

fig.update_layout(
    title_font=dict(size=28, family='Arial', color='#333'),
    font=dict(size=12, family='Arial'),
    coloraxis_colorbar=dict(
        title='Case Count',
        ticks="outside"
    ),
    height=900,
    margin=dict(l=40, r=40, t=80, b=40)
)

#improve animation speed
fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 180
fig.layout.updatemenus[0].buttons[0].args[1]["transition"]["duration"] = 150

fig.show()

